### ISSUE TITLE
Rip out history

### ISSUE THREAD

**Issue by gthompson** [geoscience-community-codes/GISMO#29]
_From @CelsoReyes on August 1, 2015 22:37_

Remove automatic history tracking from the waveform objects.

Reasoning: Bloat, processing time, and code maintainability.

_Copied from original issue: giseislab/gismotools#41_

**Comment by gthompson** [comment]
_From @CelsoReyes on August 13, 2015 14:12_

The history-related functions still work, but I've removed the option for "Nohist" and taken history recording out of almost all base waveform functions.  (ex. add, subtract, etc.)  These changes were merged into the main when I merged the scnl_rework branch back in.

**Comment by CelsoReyes** [comment]
### Executive summary of History tracking

#### History of history

History tracking was added to the waveform objects, and had been incorporated into most activities, including simple mathamatics.  It has been capable of not only storing summaries of what had happened to the Waveform, but could also store other objects, such as filters, that were used.  Because several operations were complex, then history was augmented with a flag that told it when it should effectively be skipped.

#### Problem

History takes time to apply, and takes up space in a waveform.  It was applied inconsistently, and workarounds were used that allowed history to be bypassed.  

#### Solution

History is now something that can be added manually, and some more complicated manipulations will still modify it. 

#### Waveform

History is implemented as a Nx2 cell.
**waveform/addhistory()** 
`W = addhistory(W, 'historical message');` automatically appends a cell with `{historical message, now}` 
**waveform/history()** 
`[what, when] = history(W);` will return cells, where 'what' is messages and 'when' is strings of times.
**waveform/get()**
historycell = get(W,'history'); will return the raw (Nx2) cell content for history
`waveform/clearhistory()`

#### Trace history-related methods

History is implemented as an N-length struct with fields `what` & `when`
**Trace.addhistory()**
`T = T.addhistory('historical message')`  automatically adds the historical message (`what`) with the `when` of the current date & time.

**Trace.history()**
`histstruct = T.history()`
`histstruct = T.history(N)`  returns the Nth element of the history. This is for free. Only works on when `numel(T) == 1`.

**Trace.clearhistory()** `T = T.clearhistory;` leaves an empty structure.

#### Trace additional notes

Because history is a field in Trace, accessing it from multiple traces will act as though you've made multiple requests.  This might cause a confusing bug, since it will only store the history of the last object of the array.

You can join them together as cells `{T.history}` or as one continuous 1xN struct `[T.history]`
