### ISSUE TITLE
tests not running

### ISSUE THREAD

**Issue by CelsoReyes** [geoscience-community-codes/GISMO#38]
I'm not able to run tests now that they've been put into a package, even after trying to import tests. do they run for you?

runtests()
runtests('test_TraceData')

**Comment by gthompson** [comment]
Worked on my laptop but not at GI on earlier version of matlab. 

Let's unpackage.

-----Original Message-----

**Comment by gthompson** [comment]
Unpackaged. Moved +test to tests. Now able to run:
    run(amplitude_spectrum_test)

Result it runs (but fails - due to fsamp property now being renamed in waveform):

Running amplitude_spectrum_test

# 

Uncaught error occurred in amplitude_spectrum_test/testFunctionOne.
The remainder of the test method will not run to completion.

```
--------------
Error Details:
--------------
Undefined function or variable 'fsamp'.

Error in amplitude_spectrum_test>testFunctionOne (line 10)
t=0:1/fsamp:60; % 60s of data, 100Hz sampling rate
```

# 

.
Done amplitude_spectrum_test

---

Failure Summary:

```
 Name                                     Failed  Incomplete  Reason(s)
========================================================================
 amplitude_spectrum_test/testFunctionOne    X         X       Errored.
```

ans = 

  TestResult with properties:

```
      Name: 'amplitude_spectrum_test/testFunctionOne'
    Passed: 0
    Failed: 1
Incomplete: 1
  Duration: 0.0154
```

Totals:
   0 Passed, 1 Failed, 1 Incomplete.
   0.015359 seconds testing time.
